### ISSUE TITLE
Checkpoint system

### ISSUE THREAD

**Issue by EntropyMonkey** [EntropyMonkey/Staying-Alive#16]
Checkpoints can be set by the levelbuilders easily. When the player dies, he is reset at the last checkpoint. When the player dies, the collectibles and the destroyable walls between the current and the next checkpoint should be reset too. The stuff which should be reset other than the player should be able to set easily by the levelbuilders.

**Comment by attacksnack** [comment]
1. Should checkpoints be visible for players? ("New checkpoint reached")
2. How should checkpoints be triggered: Should the player be at a specific position or just have i.e. greater x-coordinate

**Comment by attacksnack** [comment]
Now we just need to set up WHERE the checkpoints should be and WHICH pillars should be recreated when that checkpoint is loaded

**Comment by attacksnack** [comment]
Now it should be done :)
Note that so far only pillars are recreated (not collectibles) and only the pillars in between the checkpoints are recreated
